[api]
port = 54321

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "exp://localhost:8081"
additional_redirect_urls = ["exp://localhost:8081", "gymcoaching://"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
