export type MuscleGroup =
  | 'Chest'
  | 'Back'
  | 'Legs'
  | 'Shoulders'
  | 'Arms'
  | 'Core'
  | 'Cardio';

export type LibraryExercise = {
  name: string;
  muscle: MuscleGroup;
};

export const MUSCLE_GROUPS: MuscleGroup[] = [
  'Chest', 'Back', 'Legs', 'Shoulders', 'Arms', 'Core', 'Cardio',
];

export const EXERCISE_LIBRARY: LibraryExercise[] = [
  // ── Chest ──────────────────────────────────────────────────────────────────
  { name: 'Bench Press', muscle: 'Chest' },
  { name: 'Incline Bench Press', muscle: 'Chest' },
  { name: 'Decline Bench Press', muscle: 'Chest' },
  { name: 'Close Grip Bench Press', muscle: 'Chest' },
  { name: 'Reverse Grip Bench Press', muscle: 'Chest' },
  { name: 'Spoto Press', muscle: 'Chest' },
  { name: 'Floor Press', muscle: 'Chest' },
  { name: 'Barbell Floor Press', muscle: 'Chest' },
  { name: 'Smith Machine Bench Press', muscle: 'Chest' },
  { name: 'Dumbbell Chest Press', muscle: 'Chest' },
  { name: 'Incline Dumbbell Press', muscle: 'Chest' },
  { name: 'Decline Dumbbell Press', muscle: 'Chest' },
  { name: 'Hex Press', muscle: 'Chest' },
  { name: 'Squeeze Press', muscle: 'Chest' },
  { name: 'Chest Fly', muscle: 'Chest' },
  { name: 'Incline Chest Fly', muscle: 'Chest' },
  { name: 'Dumbbell Pullover', muscle: 'Chest' },
  { name: 'Cable Crossover', muscle: 'Chest' },
  { name: 'Low to High Cable Fly', muscle: 'Chest' },
  { name: 'High to Low Cable Fly', muscle: 'Chest' },
  { name: 'Single Arm Cable Crossover', muscle: 'Chest' },
  { name: 'Cable Chest Press', muscle: 'Chest' },
  { name: 'Pec Deck', muscle: 'Chest' },
  { name: 'Machine Chest Press', muscle: 'Chest' },
  { name: 'Iso-Lateral Chest Press', muscle: 'Chest' },
  { name: 'Landmine Press', muscle: 'Chest' },
  { name: 'Push Up', muscle: 'Chest' },
  { name: 'Wide Push Up', muscle: 'Chest' },
  { name: 'Diamond Push Up', muscle: 'Chest' },
  { name: 'Decline Push Up', muscle: 'Chest' },
  { name: 'Archer Push Up', muscle: 'Chest' },
  { name: 'Plyometric Push Up', muscle: 'Chest' },
  { name: 'Chest Dips', muscle: 'Chest' },
  { name: 'Svend Press', muscle: 'Chest' },

  // ── Back ───────────────────────────────────────────────────────────────────
  { name: 'Pull Up', muscle: 'Back' },
  { name: 'Chin Up', muscle: 'Back' },
  { name: 'Wide Grip Pull Up', muscle: 'Back' },
  { name: 'Neutral Grip Pull Up', muscle: 'Back' },
  { name: 'Assisted Pull Up', muscle: 'Back' },
  { name: 'Inverted Row', muscle: 'Back' },
  { name: 'TRX Row', muscle: 'Back' },
  { name: 'Lat Pulldown', muscle: 'Back' },
  { name: 'Wide Grip Lat Pulldown', muscle: 'Back' },
  { name: 'Close Grip Lat Pulldown', muscle: 'Back' },
  { name: 'V-Bar Pulldown', muscle: 'Back' },
  { name: 'Single Arm Pulldown', muscle: 'Back' },
  { name: 'Straight Arm Pulldown', muscle: 'Back' },
  { name: 'Cable Pullover', muscle: 'Back' },
  { name: 'Seated Cable Row', muscle: 'Back' },
  { name: 'Single Arm Cable Row', muscle: 'Back' },
  { name: 'Low Cable Row', muscle: 'Back' },
  { name: 'Bent Over Barbell Row', muscle: 'Back' },
  { name: 'Reverse Grip Bent Over Row', muscle: 'Back' },
  { name: 'Pendlay Row', muscle: 'Back' },
  { name: 'Single Arm Dumbbell Row', muscle: 'Back' },
  { name: 'Chest Supported Row', muscle: 'Back' },
  { name: 'T-Bar Row', muscle: 'Back' },
  { name: 'Seal Row', muscle: 'Back' },
  { name: 'Meadows Row', muscle: 'Back' },
  { name: 'Renegade Row', muscle: 'Back' },
  { name: 'Deadlift', muscle: 'Back' },
  { name: 'Sumo Deadlift', muscle: 'Back' },
  { name: 'Romanian Deadlift', muscle: 'Back' },
  { name: 'Stiff Leg Deadlift', muscle: 'Back' },
  { name: 'Single Leg Romanian Deadlift', muscle: 'Back' },
  { name: 'Trap Bar Deadlift', muscle: 'Back' },
  { name: 'Rack Pull', muscle: 'Back' },
  { name: 'Face Pull', muscle: 'Back' },
  { name: 'Barbell Shrug', muscle: 'Back' },
  { name: 'Dumbbell Shrug', muscle: 'Back' },
  { name: 'Hyperextension', muscle: 'Back' },
  { name: 'Good Morning', muscle: 'Back' },
  { name: 'Superman', muscle: 'Back' },
  { name: 'Bird Dog', muscle: 'Back' },

  // ── Legs ───────────────────────────────────────────────────────────────────
  { name: 'Squat', muscle: 'Legs' },
  { name: 'Front Squat', muscle: 'Legs' },
  { name: 'Sumo Squat', muscle: 'Legs' },
  { name: 'Goblet Squat', muscle: 'Legs' },
  { name: 'Zercher Squat', muscle: 'Legs' },
  { name: 'Pause Squat', muscle: 'Legs' },
  { name: 'Box Squat', muscle: 'Legs' },
  { name: 'Pistol Squat', muscle: 'Legs' },
  { name: 'Sissy Squat', muscle: 'Legs' },
  { name: 'Wall Sit', muscle: 'Legs' },
  { name: 'Bulgarian Split Squat', muscle: 'Legs' },
  { name: 'Romanian Split Squat', muscle: 'Legs' },
  { name: 'Smith Machine Squat', muscle: 'Legs' },
  { name: 'Hack Squat', muscle: 'Legs' },
  { name: 'Leg Press', muscle: 'Legs' },
  { name: 'Single Leg Press', muscle: 'Legs' },
  { name: 'Lunges', muscle: 'Legs' },
  { name: 'Walking Lunges', muscle: 'Legs' },
  { name: 'Reverse Lunge', muscle: 'Legs' },
  { name: 'Lateral Lunge', muscle: 'Legs' },
  { name: 'Curtsy Lunge', muscle: 'Legs' },
  { name: 'Jumping Lunge', muscle: 'Legs' },
  { name: 'Leg Curl', muscle: 'Legs' },
  { name: 'Lying Leg Curl', muscle: 'Legs' },
  { name: 'Nordic Curl', muscle: 'Legs' },
  { name: 'Leg Extension', muscle: 'Legs' },
  { name: 'Cable Pull Through', muscle: 'Legs' },
  { name: 'Hip Thrust', muscle: 'Legs' },
  { name: 'Barbell Hip Thrust', muscle: 'Legs' },
  { name: 'Glute Bridge', muscle: 'Legs' },
  { name: 'Single Leg Glute Bridge', muscle: 'Legs' },
  { name: 'Cable Kickback', muscle: 'Legs' },
  { name: 'Donkey Kick', muscle: 'Legs' },
  { name: 'Fire Hydrant', muscle: 'Legs' },
  { name: 'Hip Abduction', muscle: 'Legs' },
  { name: 'Hip Adduction', muscle: 'Legs' },
  { name: 'Lateral Band Walk', muscle: 'Legs' },
  { name: 'Monster Walk', muscle: 'Legs' },
  { name: 'Step Up', muscle: 'Legs' },
  { name: 'Box Step Up', muscle: 'Legs' },
  { name: 'Calf Raise', muscle: 'Legs' },
  { name: 'Seated Calf Raise', muscle: 'Legs' },
  { name: 'Leg Press Calf Raise', muscle: 'Legs' },

  // ── Shoulders ──────────────────────────────────────────────────────────────
  { name: 'Overhead Press', muscle: 'Shoulders' },
  { name: 'Seated Barbell Press', muscle: 'Shoulders' },
  { name: 'Dumbbell Shoulder Press', muscle: 'Shoulders' },
  { name: 'Seated Dumbbell Press', muscle: 'Shoulders' },
  { name: 'Arnold Press', muscle: 'Shoulders' },
  { name: 'Push Press', muscle: 'Shoulders' },
  { name: 'Smith Machine Shoulder Press', muscle: 'Shoulders' },
  { name: 'Machine Shoulder Press', muscle: 'Shoulders' },
  { name: 'Cuban Press', muscle: 'Shoulders' },
  { name: 'Lateral Raise', muscle: 'Shoulders' },
  { name: 'Cable Lateral Raise', muscle: 'Shoulders' },
  { name: 'Machine Lateral Raise', muscle: 'Shoulders' },
  { name: 'Leaning Lateral Raise', muscle: 'Shoulders' },
  { name: 'Front Raise', muscle: 'Shoulders' },
  { name: 'Plate Front Raise', muscle: 'Shoulders' },
  { name: 'Cable Front Raise', muscle: 'Shoulders' },
  { name: 'Rear Delt Fly', muscle: 'Shoulders' },
  { name: 'Cable Rear Delt Fly', muscle: 'Shoulders' },
  { name: 'Machine Rear Delt Fly', muscle: 'Shoulders' },
  { name: 'Bent Over Lateral Raise', muscle: 'Shoulders' },
  { name: 'Upright Row', muscle: 'Shoulders' },
  { name: 'Cable Upright Row', muscle: 'Shoulders' },
  { name: 'Y-T-W Raises', muscle: 'Shoulders' },
  { name: 'Band Pull Apart', muscle: 'Shoulders' },
  { name: 'Pike Push Up', muscle: 'Shoulders' },
  { name: 'Handstand Push Up', muscle: 'Shoulders' },
  { name: 'Landmine Lateral Raise', muscle: 'Shoulders' },

  // ── Arms ───────────────────────────────────────────────────────────────────
  { name: 'Bicep Curl', muscle: 'Arms' },
  { name: 'Barbell Curl', muscle: 'Arms' },
  { name: 'EZ Bar Curl', muscle: 'Arms' },
  { name: 'Hammer Curl', muscle: 'Arms' },
  { name: 'Cross Body Curl', muscle: 'Arms' },
  { name: 'Pinwheel Curl', muscle: 'Arms' },
  { name: 'Concentration Curl', muscle: 'Arms' },
  { name: 'Preacher Curl', muscle: 'Arms' },
  { name: 'Cable Curl', muscle: 'Arms' },
  { name: 'Rope Curl', muscle: 'Arms' },
  { name: 'Cable Hammer Curl', muscle: 'Arms' },
  { name: 'Incline Dumbbell Curl', muscle: 'Arms' },
  { name: 'Spider Curl', muscle: 'Arms' },
  { name: 'Zottman Curl', muscle: 'Arms' },
  { name: 'Drag Curl', muscle: 'Arms' },
  { name: 'Machine Bicep Curl', muscle: 'Arms' },
  { name: '21s', muscle: 'Arms' },
  { name: 'Reverse Curl', muscle: 'Arms' },
  { name: 'Wrist Curl', muscle: 'Arms' },
  { name: 'Reverse Wrist Curl', muscle: 'Arms' },
  { name: 'Tricep Pushdown', muscle: 'Arms' },
  { name: 'Rope Pushdown', muscle: 'Arms' },
  { name: 'Single Arm Tricep Pushdown', muscle: 'Arms' },
  { name: 'Skull Crusher', muscle: 'Arms' },
  { name: 'Overhead Tricep Extension', muscle: 'Arms' },
  { name: 'Cable Overhead Tricep Extension', muscle: 'Arms' },
  { name: 'Tricep Kickback', muscle: 'Arms' },
  { name: 'Tricep Dips', muscle: 'Arms' },
  { name: 'Tate Press', muscle: 'Arms' },
  { name: 'JM Press', muscle: 'Arms' },
  { name: 'Machine Tricep Extension', muscle: 'Arms' },

  // ── Core ───────────────────────────────────────────────────────────────────
  { name: 'Plank', muscle: 'Core' },
  { name: 'Side Plank', muscle: 'Core' },
  { name: 'RKC Plank', muscle: 'Core' },
  { name: 'Plank Hip Dip', muscle: 'Core' },
  { name: 'Hollow Body Hold', muscle: 'Core' },
  { name: 'Hollow Rock', muscle: 'Core' },
  { name: 'L-Sit', muscle: 'Core' },
  { name: 'Bear Crawl', muscle: 'Core' },
  { name: 'Inchworm', muscle: 'Core' },
  { name: 'Crunch', muscle: 'Core' },
  { name: 'Sit Up', muscle: 'Core' },
  { name: 'Toe Touch', muscle: 'Core' },
  { name: 'Reverse Crunch', muscle: 'Core' },
  { name: 'Bicycle Crunch', muscle: 'Core' },
  { name: 'Seated Ab Machine', muscle: 'Core' },
  { name: 'Stability Ball Crunch', muscle: 'Core' },
  { name: 'Leg Raise', muscle: 'Core' },
  { name: 'Hanging Leg Raise', muscle: 'Core' },
  { name: 'Hanging Knee Raise', muscle: 'Core' },
  { name: 'Toes to Bar', muscle: 'Core' },
  { name: 'Flutter Kicks', muscle: 'Core' },
  { name: 'Scissor Kicks', muscle: 'Core' },
  { name: 'V-Up', muscle: 'Core' },
  { name: 'Dragon Flag', muscle: 'Core' },
  { name: 'Russian Twist', muscle: 'Core' },
  { name: 'Woodchop', muscle: 'Core' },
  { name: 'Pallof Press', muscle: 'Core' },
  { name: 'Landmine Rotation', muscle: 'Core' },
  { name: 'Cable Crunch', muscle: 'Core' },
  { name: 'Ab Wheel Rollout', muscle: 'Core' },
  { name: 'Mountain Climber', muscle: 'Core' },
  { name: 'Dead Bug', muscle: 'Core' },
  { name: 'Copenhagen Plank', muscle: 'Core' },
  { name: 'Windshield Wiper', muscle: 'Core' },
  { name: 'Suitcase Carry', muscle: 'Core' },

  // ── Cardio / Full Body ─────────────────────────────────────────────────────
  { name: 'Burpees', muscle: 'Cardio' },
  { name: 'Jumping Jacks', muscle: 'Cardio' },
  { name: 'Jump Rope', muscle: 'Cardio' },
  { name: 'Double Unders', muscle: 'Cardio' },
  { name: 'Box Jump', muscle: 'Cardio' },
  { name: 'Broad Jump', muscle: 'Cardio' },
  { name: 'Depth Jump', muscle: 'Cardio' },
  { name: 'Lateral Bound', muscle: 'Cardio' },
  { name: 'Skater Jump', muscle: 'Cardio' },
  { name: 'Tuck Jump', muscle: 'Cardio' },
  { name: 'Sprint', muscle: 'Cardio' },
  { name: 'Lateral Shuffle', muscle: 'Cardio' },
  { name: 'Power Skip', muscle: 'Cardio' },
  { name: 'High Knees', muscle: 'Cardio' },
  { name: 'Jump Squat', muscle: 'Cardio' },
  { name: 'Jumping Lunge', muscle: 'Cardio' },
  { name: 'Plyometric Push Up', muscle: 'Cardio' },
  { name: 'Battle Ropes', muscle: 'Cardio' },
  { name: 'Sled Push', muscle: 'Cardio' },
  { name: 'Sled Pull', muscle: 'Cardio' },
  { name: 'Tire Flip', muscle: 'Cardio' },
  { name: 'Farmer\'s Walk', muscle: 'Cardio' },
  { name: 'Sandbag Carry', muscle: 'Cardio' },
  { name: 'Agility Ladder', muscle: 'Cardio' },
  { name: 'Cone Drill', muscle: 'Cardio' },
  { name: 'Kettlebell Swing', muscle: 'Cardio' },
  { name: 'Kettlebell Snatch', muscle: 'Cardio' },
  { name: 'Turkish Get Up', muscle: 'Cardio' },
  { name: 'Thruster', muscle: 'Cardio' },
  { name: 'Clean and Jerk', muscle: 'Cardio' },
  { name: 'Power Clean', muscle: 'Cardio' },
  { name: 'Hang Clean', muscle: 'Cardio' },
  { name: 'Wall Ball', muscle: 'Cardio' },
  { name: 'Medicine Ball Slam', muscle: 'Cardio' },
  { name: 'Rotational Medicine Ball Throw', muscle: 'Cardio' },
  { name: 'Man Maker', muscle: 'Cardio' },
  { name: 'Shadow Boxing', muscle: 'Cardio' },
  { name: 'Treadmill Run', muscle: 'Cardio' },
  { name: 'Stair Climber', muscle: 'Cardio' },
  { name: 'Elliptical', muscle: 'Cardio' },
  { name: 'Rowing Machine', muscle: 'Cardio' },
  { name: 'Assault Bike', muscle: 'Cardio' },
  { name: 'Stationary Bike', muscle: 'Cardio' },
];
