export type MachineDifficulty = 'beginner' | 'intermediate' | 'advanced';

export type MachineExercise = {
  name: string;
  primary: string[];
  secondary: string[];
  difficulty: MachineDifficulty;
};

export type GymMachine = {
  id: string;
  name: string;
  icon: string;
  category: 'Free Weights' | 'Cable' | 'Machine' | 'Bodyweight' | 'Accessories';
  exercises: MachineExercise[];
};

export const GYM_MACHINES: GymMachine[] = [
  // ─── FREE WEIGHTS ────────────────────────────────────────────────────────────
  {
    id: 'barbell_rack',
    name: 'Barbell / Squat Rack',
    icon: 'barbell-outline',
    category: 'Free Weights',
    exercises: [
      // Squats
      { name: 'Back Squat',                primary: ['Quads'],                    secondary: ['Glutes', 'Hamstrings', 'Core'],       difficulty: 'intermediate' },
      { name: 'Front Squat',               primary: ['Quads'],                    secondary: ['Core', 'Upper Back'],                 difficulty: 'advanced' },
      { name: 'Overhead Squat',            primary: ['Quads'],                    secondary: ['Core', 'Shoulders', 'Upper Back'],    difficulty: 'advanced' },
      { name: 'Zercher Squat',             primary: ['Quads', 'Glutes'],          secondary: ['Core', 'Biceps'],                     difficulty: 'advanced' },
      { name: 'Pause Squat',               primary: ['Quads'],                    secondary: ['Glutes', 'Core'],                     difficulty: 'advanced' },
      { name: 'Box Squat',                 primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings', 'Core'],                 difficulty: 'intermediate' },
      { name: 'Barbell Hack Squat',        primary: ['Quads'],                    secondary: ['Glutes', 'Calves'],                   difficulty: 'intermediate' },
      { name: 'Anderson Squat',            primary: ['Quads', 'Glutes'],          secondary: ['Core', 'Hamstrings'],                 difficulty: 'advanced' },
      { name: 'Barbell Jump Squat',        primary: ['Quads', 'Glutes'],          secondary: ['Calves', 'Core'],                     difficulty: 'intermediate' },
      { name: 'Barbell Cossack Squat',     primary: ['Adductors', 'Quads'],       secondary: ['Glutes', 'Core'],                     difficulty: 'advanced' },
      // Lunges / Single-leg
      { name: 'Barbell Lunge',             primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings'],                         difficulty: 'intermediate' },
      { name: 'Barbell Reverse Lunge',     primary: ['Glutes', 'Quads'],          secondary: ['Hamstrings'],                         difficulty: 'intermediate' },
      { name: 'Barbell Walking Lunge',     primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings', 'Core'],                 difficulty: 'intermediate' },
      { name: 'Barbell Split Squat',       primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings'],                         difficulty: 'intermediate' },
      { name: 'Barbell Bulgarian Split',   primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings', 'Core'],                 difficulty: 'advanced' },
      { name: 'Barbell Step-Up',           primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings', 'Calves'],               difficulty: 'intermediate' },
      { name: 'Barbell Lateral Lunge',     primary: ['Adductors', 'Glutes'],      secondary: ['Quads'],                              difficulty: 'intermediate' },
      { name: 'Barbell Overhead Lunge',    primary: ['Quads', 'Core'],            secondary: ['Glutes', 'Shoulders'],                difficulty: 'advanced' },
      // Deadlifts / Hip hinge
      { name: 'Conventional Deadlift',     primary: ['Hamstrings', 'Glutes'],     secondary: ['Lower Back', 'Traps', 'Core'],        difficulty: 'intermediate' },
      { name: 'Sumo Deadlift',             primary: ['Glutes', 'Inner Thighs'],   secondary: ['Hamstrings', 'Lower Back'],            difficulty: 'intermediate' },
      { name: 'Romanian Deadlift',         primary: ['Hamstrings'],               secondary: ['Glutes', 'Lower Back'],               difficulty: 'intermediate' },
      { name: 'Stiff Leg Deadlift',        primary: ['Hamstrings'],               secondary: ['Glutes', 'Lower Back', 'Calves'],     difficulty: 'intermediate' },
      { name: 'Deficit Deadlift',          primary: ['Hamstrings', 'Glutes'],     secondary: ['Lower Back', 'Core'],                 difficulty: 'advanced' },
      { name: 'Sumo Romanian Deadlift',    primary: ['Glutes', 'Adductors'],      secondary: ['Hamstrings', 'Lower Back'],            difficulty: 'intermediate' },
      { name: 'Single Leg Romanian DL',    primary: ['Hamstrings'],               secondary: ['Glutes', 'Core'],                     difficulty: 'intermediate' },
      { name: 'Rack Pull',                 primary: ['Traps', 'Erectors'],        secondary: ['Glutes', 'Hamstrings'],               difficulty: 'intermediate' },
      { name: 'Good Morning',              primary: ['Hamstrings', 'Erectors'],   secondary: ['Glutes'],                             difficulty: 'intermediate' },
      { name: 'Good Morning Squat',        primary: ['Hamstrings', 'Quads'],      secondary: ['Erectors', 'Glutes'],                 difficulty: 'advanced' },
      { name: 'Barbell Suitcase Deadlift', primary: ['Glutes', 'Core'],           secondary: ['Hamstrings', 'Traps'],                difficulty: 'intermediate' },
      // Hip / Glutes / Lower
      { name: 'Barbell Hip Thrust',        primary: ['Glutes'],                   secondary: ['Hamstrings', 'Core'],                 difficulty: 'beginner' },
      { name: 'Barbell Glute Bridge',      primary: ['Glutes'],                   secondary: ['Hamstrings', 'Core'],                 difficulty: 'beginner' },
      { name: 'Barbell Calf Raise',        primary: ['Calves'],                   secondary: [],                                     difficulty: 'beginner' },
      // Power / Olympic
      { name: 'Power Clean',               primary: ['Full Body', 'Glutes'],      secondary: ['Shoulders', 'Traps', 'Core'],         difficulty: 'advanced' },
      { name: 'Hang Clean',                primary: ['Full Body', 'Glutes'],      secondary: ['Traps', 'Core', 'Shoulders'],         difficulty: 'advanced' },
      { name: 'Power Snatch',              primary: ['Full Body', 'Shoulders'],   secondary: ['Glutes', 'Core', 'Traps'],            difficulty: 'advanced' },
      { name: 'Hang Power Clean',          primary: ['Glutes', 'Traps'],          secondary: ['Shoulders', 'Core'],                  difficulty: 'advanced' },
      { name: 'Barbell Thruster',          primary: ['Quads', 'Shoulders'],       secondary: ['Glutes', 'Triceps', 'Core'],          difficulty: 'intermediate' },
      // Chest / Bench
      { name: 'Barbell Bench Press',       primary: ['Chest'],                    secondary: ['Triceps', 'Front Delts'],             difficulty: 'beginner' },
      { name: 'Incline Bench Press',       primary: ['Upper Chest'],              secondary: ['Triceps', 'Front Delts'],             difficulty: 'intermediate' },
      { name: 'Decline Bench Press',       primary: ['Lower Chest'],              secondary: ['Triceps', 'Front Delts'],             difficulty: 'intermediate' },
      { name: 'Close Grip Bench Press',    primary: ['Triceps'],                  secondary: ['Chest', 'Front Delts'],               difficulty: 'intermediate' },
      { name: 'Wide Grip Bench Press',     primary: ['Chest'],                    secondary: ['Front Delts'],                        difficulty: 'intermediate' },
      { name: 'Paused Bench Press',        primary: ['Chest'],                    secondary: ['Triceps', 'Front Delts'],             difficulty: 'intermediate' },
      { name: 'Floor Press',               primary: ['Chest', 'Triceps'],         secondary: ['Front Delts'],                        difficulty: 'intermediate' },
      // Overhead / Shoulders
      { name: 'Overhead Press',            primary: ['Side Delts'],               secondary: ['Triceps', 'Front Delts', 'Core'],     difficulty: 'intermediate' },
      { name: 'Push Press',                primary: ['Side Delts'],               secondary: ['Triceps', 'Quads', 'Core'],           difficulty: 'intermediate' },
      { name: 'Bradford Press',            primary: ['Side Delts', 'Front Delts'],secondary: ['Triceps'],                            difficulty: 'advanced' },
      { name: 'Behind-Neck Press',         primary: ['Rear Delts', 'Side Delts'], secondary: ['Triceps'],                            difficulty: 'advanced' },
      { name: 'Cuban Press',               primary: ['Rear Delts', 'Rotator Cuff'],secondary: ['Side Delts'],                        difficulty: 'intermediate' },
      { name: 'Landmine Press',            primary: ['Front Delts', 'Chest'],     secondary: ['Triceps', 'Core'],                    difficulty: 'intermediate' },
      { name: 'Barbell Front Raise',       primary: ['Front Delts'],              secondary: ['Side Delts'],                         difficulty: 'beginner' },
      { name: 'Barbell Upright Row',       primary: ['Side Delts', 'Traps'],      secondary: ['Biceps', 'Rear Delts'],               difficulty: 'beginner' },
      // Triceps
      { name: 'Skull Crusher',             primary: ['Triceps'],                  secondary: [],                                     difficulty: 'intermediate' },
      { name: 'JM Press',                  primary: ['Triceps'],                  secondary: ['Chest'],                              difficulty: 'intermediate' },
      { name: 'Overhead Tricep Ext',       primary: ['Triceps'],                  secondary: [],                                     difficulty: 'beginner' },
      // Back / Rows
      { name: 'Bent-Over Row',             primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps', 'Rear Delts'],               difficulty: 'intermediate' },
      { name: 'Pendlay Row',               primary: ['Lats', 'Rhomboids'],        secondary: ['Rear Delts', 'Biceps', 'Core'],       difficulty: 'intermediate' },
      { name: 'Yates Row (Underhand)',      primary: ['Lats'],                     secondary: ['Biceps', 'Rhomboids'],                difficulty: 'intermediate' },
      { name: 'Meadows Row',               primary: ['Lats'],                     secondary: ['Rhomboids', 'Biceps'],                difficulty: 'intermediate' },
      { name: 'Landmine Row',              primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps', 'Core'],                     difficulty: 'intermediate' },
      { name: 'Inverted Row (bar in rack)',  primary: ['Lats', 'Rhomboids'],       secondary: ['Biceps', 'Core'],                     difficulty: 'beginner' },
      { name: 'Prone Row (incline bench)', primary: ['Lats', 'Rhomboids'],        secondary: ['Rear Delts', 'Biceps'],               difficulty: 'beginner' },
      { name: 'Barbell Shrug',             primary: ['Traps'],                    secondary: ['Rhomboids'],                          difficulty: 'beginner' },
      { name: 'Behind-Back Shrug',         primary: ['Traps'],                    secondary: ['Rear Delts'],                         difficulty: 'beginner' },
      // Arms
      { name: 'Barbell Curl',              primary: ['Biceps'],                   secondary: ['Forearms'],                           difficulty: 'beginner' },
      { name: 'Barbell Reverse Curl',      primary: ['Brachialis', 'Forearms'],   secondary: ['Biceps'],                             difficulty: 'beginner' },
      { name: 'Barbell Drag Curl',         primary: ['Biceps'],                   secondary: ['Brachialis'],                         difficulty: 'intermediate' },
      { name: 'Barbell Preacher Curl',     primary: ['Biceps'],                   secondary: ['Brachialis'],                         difficulty: 'beginner' },
      { name: 'Barbell Wrist Curl',        primary: ['Forearms'],                 secondary: [],                                     difficulty: 'beginner' },
      { name: 'Barbell Wrist Extension',   primary: ['Forearms'],                 secondary: [],                                     difficulty: 'beginner' },
      // Core
      { name: 'Barbell Rollout',           primary: ['Abs'],                      secondary: ['Lats', 'Triceps'],                    difficulty: 'advanced' },
    ],
  },
  {
    id: 'dumbbells',
    name: 'Dumbbells',
    icon: 'barbell-outline',
    category: 'Free Weights',
    exercises: [
      // Chest
      { name: 'DB Bench Press',            primary: ['Chest'],                    secondary: ['Triceps', 'Front Delts'],             difficulty: 'beginner' },
      { name: 'Incline DB Press',          primary: ['Upper Chest'],              secondary: ['Front Delts', 'Triceps'],             difficulty: 'beginner' },
      { name: 'Decline DB Press',          primary: ['Lower Chest'],              secondary: ['Triceps'],                            difficulty: 'beginner' },
      { name: 'DB Fly',                    primary: ['Chest'],                    secondary: ['Front Delts'],                        difficulty: 'beginner' },
      { name: 'Incline DB Fly',            primary: ['Upper Chest'],              secondary: ['Front Delts'],                        difficulty: 'beginner' },
      { name: 'DB Floor Press',            primary: ['Chest', 'Triceps'],         secondary: ['Front Delts'],                        difficulty: 'beginner' },
      { name: 'DB Pullover',               primary: ['Lats', 'Chest'],            secondary: ['Triceps', 'Core'],                    difficulty: 'intermediate' },
      { name: 'DB Svend Press',            primary: ['Inner Chest'],              secondary: ['Front Delts'],                        difficulty: 'beginner' },
      { name: 'DB Neutral Press',          primary: ['Chest', 'Triceps'],         secondary: ['Front Delts'],                        difficulty: 'beginner' },
      { name: 'DB Around the World',       primary: ['Chest'],                    secondary: ['Front Delts', 'Shoulders'],           difficulty: 'beginner' },
      { name: 'Loaded Stretch DB Fly',     primary: ['Chest'],                    secondary: ['Front Delts'],                        difficulty: 'intermediate' },
      // Shoulders
      { name: 'DB Shoulder Press (seated)',primary: ['Side Delts'],               secondary: ['Triceps', 'Front Delts'],             difficulty: 'beginner' },
      { name: 'DB Shoulder Press (standing)',primary: ['Side Delts'],             secondary: ['Triceps', 'Front Delts', 'Core'],     difficulty: 'beginner' },
      { name: 'Arnold Press',              primary: ['Side Delts', 'Front Delts'],secondary: ['Triceps', 'Rear Delts'],              difficulty: 'beginner' },
      { name: 'Lateral Raise',             primary: ['Side Delts'],               secondary: ['Traps'],                              difficulty: 'beginner' },
      { name: 'Lateral Raise (seated)',    primary: ['Side Delts'],               secondary: ['Traps'],                              difficulty: 'beginner' },
      { name: 'Leaning Lateral Raise',     primary: ['Side Delts'],               secondary: ['Traps'],                              difficulty: 'intermediate' },
      { name: 'Front Raise',               primary: ['Front Delts'],              secondary: ['Side Delts'],                         difficulty: 'beginner' },
      { name: 'Alternating Front Raise',   primary: ['Front Delts'],              secondary: ['Core'],                               difficulty: 'beginner' },
      { name: 'Bent-Over Rear Delt Raise', primary: ['Rear Delts'],               secondary: ['Rhomboids', 'Traps'],                 difficulty: 'beginner' },
      { name: 'Lying Rear Delt Raise',     primary: ['Rear Delts'],               secondary: ['Rhomboids'],                          difficulty: 'beginner' },
      { name: 'DB Upright Row',            primary: ['Side Delts', 'Traps'],      secondary: ['Biceps', 'Rear Delts'],               difficulty: 'beginner' },
      { name: 'DB Cuban Press',            primary: ['Rear Delts', 'Rotator Cuff'],secondary: ['Side Delts'],                        difficulty: 'intermediate' },
      { name: 'DB Y Raise (prone)',        primary: ['Lower Traps', 'Rear Delts'],secondary: ['Rhomboids'],                          difficulty: 'beginner' },
      { name: 'DB T Raise (prone)',        primary: ['Rear Delts', 'Mid Traps'],  secondary: ['Rhomboids'],                          difficulty: 'beginner' },
      { name: 'DB W Raise (prone)',        primary: ['Rotator Cuff'],             secondary: ['Rear Delts'],                         difficulty: 'beginner' },
      // Biceps
      { name: 'DB Curl',                   primary: ['Biceps'],                   secondary: ['Forearms'],                           difficulty: 'beginner' },
      { name: 'Hammer Curl',               primary: ['Brachialis'],               secondary: ['Biceps', 'Forearms'],                 difficulty: 'beginner' },
      { name: 'Concentration Curl',        primary: ['Biceps'],                   secondary: ['Brachialis'],                         difficulty: 'beginner' },
      { name: 'Incline DB Curl',           primary: ['Biceps'],                   secondary: ['Brachialis'],                         difficulty: 'intermediate' },
      { name: 'Zottman Curl',              primary: ['Biceps', 'Brachialis'],     secondary: ['Forearms'],                           difficulty: 'intermediate' },
      { name: 'Spider Curl',               primary: ['Biceps'],                   secondary: [],                                     difficulty: 'intermediate' },
      { name: 'Cross Body Curl',           primary: ['Brachialis'],               secondary: ['Biceps', 'Forearms'],                 difficulty: 'beginner' },
      { name: 'DB Drag Curl',              primary: ['Biceps'],                   secondary: ['Brachialis'],                         difficulty: 'intermediate' },
      { name: 'DB Reverse Curl',           primary: ['Brachialis', 'Forearms'],   secondary: ['Biceps'],                             difficulty: 'beginner' },
      { name: 'Pinwheel Curl',             primary: ['Brachialis', 'Forearms'],   secondary: ['Biceps'],                             difficulty: 'beginner' },
      { name: 'DB Preacher Curl',          primary: ['Biceps'],                   secondary: ['Brachialis'],                         difficulty: 'beginner' },
      // Triceps
      { name: 'DB Overhead Tricep Ext',    primary: ['Triceps'],                  secondary: [],                                     difficulty: 'beginner' },
      { name: 'Single Arm OH Tricep Ext',  primary: ['Triceps'],                  secondary: [],                                     difficulty: 'beginner' },
      { name: 'Tricep Kickback',           primary: ['Triceps'],                  secondary: [],                                     difficulty: 'beginner' },
      { name: 'DB Skull Crusher',          primary: ['Triceps'],                  secondary: [],                                     difficulty: 'intermediate' },
      { name: 'DB Lying Tricep Ext',       primary: ['Triceps'],                  secondary: ['Chest'],                              difficulty: 'intermediate' },
      { name: 'DB Close Grip Floor Press', primary: ['Triceps', 'Chest'],         secondary: ['Front Delts'],                        difficulty: 'beginner' },
      // Back
      { name: 'Single Arm DB Row',         primary: ['Lats'],                     secondary: ['Rhomboids', 'Biceps'],                difficulty: 'beginner' },
      { name: 'Chest Supported DB Row',    primary: ['Rhomboids', 'Lats'],        secondary: ['Rear Delts', 'Biceps'],               difficulty: 'beginner' },
      { name: 'DB Shrug',                  primary: ['Traps'],                    secondary: ['Rhomboids'],                          difficulty: 'beginner' },
      { name: 'DB Seal Row',               primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps', 'Rear Delts'],               difficulty: 'beginner' },
      { name: 'DB Bent-Over Row (bilateral)',primary: ['Lats', 'Rhomboids'],      secondary: ['Biceps'],                             difficulty: 'beginner' },
      { name: 'DB Incline Rear Delt Row',  primary: ['Rear Delts', 'Rhomboids'], secondary: ['Biceps'],                             difficulty: 'beginner' },
      // Lower body
      { name: 'Goblet Squat',              primary: ['Quads'],                    secondary: ['Glutes', 'Core'],                     difficulty: 'beginner' },
      { name: 'DB Sumo Squat',             primary: ['Glutes', 'Inner Quads'],    secondary: ['Hamstrings', 'Adductors'],            difficulty: 'beginner' },
      { name: 'DB Box Squat',              primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings', 'Core'],                 difficulty: 'beginner' },
      { name: 'DB Overhead Squat',         primary: ['Quads', 'Core'],            secondary: ['Shoulders', 'Glutes'],                difficulty: 'advanced' },
      { name: 'DB Lunge',                  primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings'],                         difficulty: 'beginner' },
      { name: 'DB Reverse Lunge',          primary: ['Glutes', 'Quads'],          secondary: ['Hamstrings'],                         difficulty: 'beginner' },
      { name: 'DB Walking Lunge',          primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings', 'Core'],                 difficulty: 'beginner' },
      { name: 'DB Lateral Lunge',          primary: ['Adductors', 'Glutes'],      secondary: ['Quads'],                              difficulty: 'beginner' },
      { name: 'DB Curtsy Lunge',           primary: ['Glutes', 'Adductors'],      secondary: ['Quads'],                              difficulty: 'beginner' },
      { name: 'DB Split Squat',            primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings'],                         difficulty: 'beginner' },
      { name: 'DB Bulgarian Split Squat',  primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings', 'Core'],                 difficulty: 'intermediate' },
      { name: 'DB Step-Up',                primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings', 'Calves'],               difficulty: 'beginner' },
      { name: 'DB Step-Up with Knee Drive',primary: ['Quads', 'Glutes'],          secondary: ['Core', 'Hip Flexors'],                difficulty: 'intermediate' },
      { name: 'DB Romanian Deadlift',      primary: ['Hamstrings'],               secondary: ['Glutes', 'Lower Back'],               difficulty: 'beginner' },
      { name: 'DB Stiff Leg Deadlift',     primary: ['Hamstrings'],               secondary: ['Glutes', 'Lower Back', 'Calves'],     difficulty: 'beginner' },
      { name: 'DB Single Leg RDL',         primary: ['Hamstrings'],               secondary: ['Glutes', 'Core'],                     difficulty: 'intermediate' },
      { name: 'DB Hip Thrust',             primary: ['Glutes'],                   secondary: ['Hamstrings'],                         difficulty: 'beginner' },
      { name: 'DB Glute Bridge',           primary: ['Glutes'],                   secondary: ['Hamstrings', 'Core'],                 difficulty: 'beginner' },
      { name: 'DB Suitcase Deadlift',      primary: ['Glutes', 'Core'],           secondary: ['Hamstrings', 'Traps'],                difficulty: 'beginner' },
      { name: 'DB Good Morning',           primary: ['Hamstrings', 'Erectors'],   secondary: ['Glutes'],                             difficulty: 'beginner' },
      { name: 'DB Calf Raise (bilateral)', primary: ['Calves'],                   secondary: [],                                     difficulty: 'beginner' },
      { name: 'Single Leg DB Calf Raise',  primary: ['Calves'],                   secondary: [],                                     difficulty: 'beginner' },
      // Full body / misc
      { name: 'DB Thruster',               primary: ['Quads', 'Shoulders'],       secondary: ['Glutes', 'Triceps', 'Core'],          difficulty: 'intermediate' },
      { name: 'DB Power Clean',            primary: ['Full Body', 'Glutes'],      secondary: ['Traps', 'Shoulders', 'Core'],         difficulty: 'advanced' },
      { name: 'DB Snatch (single arm)',     primary: ['Full Body', 'Shoulders'],   secondary: ['Glutes', 'Core', 'Traps'],            difficulty: 'advanced' },
      { name: 'DB Turkish Get-Up',         primary: ['Full Body', 'Core'],        secondary: ['Shoulders', 'Glutes'],                difficulty: 'advanced' },
      { name: 'Renegade Row',              primary: ['Lats', 'Core'],             secondary: ['Triceps', 'Rhomboids'],               difficulty: 'advanced' },
      { name: 'DB Farmer\'s Carry',        primary: ['Grip', 'Traps'],            secondary: ['Core', 'Calves'],                     difficulty: 'beginner' },
      { name: 'DB Woodchop',               primary: ['Obliques', 'Core'],         secondary: ['Shoulders'],                          difficulty: 'intermediate' },
      { name: 'DB Figure 8',               primary: ['Core', 'Glutes'],           secondary: ['Shoulders', 'Adductors'],             difficulty: 'intermediate' },
      { name: 'DB Wrist Curl',             primary: ['Forearms'],                 secondary: [],                                     difficulty: 'beginner' },
      { name: 'DB Wrist Extension',        primary: ['Forearms'],                 secondary: [],                                     difficulty: 'beginner' },
    ],
  },
  {
    id: 'ez_bar',
    name: 'EZ Bar',
    icon: 'remove-outline',
    category: 'Free Weights',
    exercises: [
      { name: 'EZ Bar Curl',              primary: ['Biceps'],                   secondary: ['Brachialis', 'Forearms'],             difficulty: 'beginner' },
      { name: 'EZ Bar Reverse Curl',      primary: ['Brachialis', 'Forearms'],   secondary: ['Biceps'],                             difficulty: 'beginner' },
      { name: 'Preacher Curl',            primary: ['Biceps'],                   secondary: ['Brachialis'],                         difficulty: 'beginner' },
      { name: 'EZ Bar Spider Curl',       primary: ['Biceps'],                   secondary: [],                                     difficulty: 'intermediate' },
      { name: 'EZ Bar Drag Curl',         primary: ['Biceps'],                   secondary: ['Brachialis'],                         difficulty: 'intermediate' },
      { name: 'EZ Bar Skull Crusher',     primary: ['Triceps'],                  secondary: [],                                     difficulty: 'intermediate' },
      { name: 'EZ Bar Lying Tricep Ext',  primary: ['Triceps'],                  secondary: [],                                     difficulty: 'intermediate' },
      { name: 'Overhead Tricep Ext',      primary: ['Triceps'],                  secondary: [],                                     difficulty: 'intermediate' },
      { name: 'Tate Press',               primary: ['Triceps'],                  secondary: ['Chest'],                              difficulty: 'intermediate' },
      { name: 'EZ Bar Upright Row',       primary: ['Side Delts', 'Traps'],      secondary: ['Biceps', 'Rear Delts'],               difficulty: 'beginner' },
      { name: 'EZ Bar Bench Press',       primary: ['Chest'],                    secondary: ['Triceps'],                            difficulty: 'intermediate' },
      { name: 'EZ Bar Close Grip Bench',  primary: ['Triceps', 'Chest'],         secondary: ['Front Delts'],                        difficulty: 'intermediate' },
      { name: 'EZ Bar Row',               primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps'],                             difficulty: 'intermediate' },
      { name: 'EZ Bar Underhand Row',     primary: ['Lats', 'Biceps'],           secondary: ['Rhomboids'],                          difficulty: 'intermediate' },
      { name: 'EZ Bar Romanian Deadlift', primary: ['Hamstrings'],               secondary: ['Glutes', 'Lower Back'],               difficulty: 'intermediate' },
      { name: 'EZ Bar Good Morning',      primary: ['Hamstrings', 'Erectors'],   secondary: ['Glutes'],                             difficulty: 'intermediate' },
      { name: 'EZ Bar Wrist Curl',        primary: ['Forearms'],                 secondary: [],                                     difficulty: 'beginner' },
      { name: 'EZ Bar Wrist Extension',   primary: ['Forearms'],                 secondary: [],                                     difficulty: 'beginner' },
    ],
  },

  // ─── CABLE ───────────────────────────────────────────────────────────────────
  {
    id: 'cable_machine',
    name: 'Cable Machine',
    icon: 'git-network-outline',
    category: 'Cable',
    exercises: [
      // Back / Pull
      { name: 'Lat Pulldown',              primary: ['Lats'],                     secondary: ['Biceps', 'Rhomboids'],                difficulty: 'beginner' },
      { name: 'Close Grip Pulldown',       primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps'],                             difficulty: 'beginner' },
      { name: 'V-Bar Pulldown',            primary: ['Lats'],                     secondary: ['Biceps', 'Rhomboids'],                difficulty: 'beginner' },
      { name: 'Rope Pulldown',             primary: ['Lats'],                     secondary: ['Biceps', 'Rear Delts'],               difficulty: 'intermediate' },
      { name: 'Underhand Grip Pulldown',   primary: ['Lats', 'Biceps'],           secondary: ['Rhomboids'],                          difficulty: 'beginner' },
      { name: 'Lean-Back Pulldown',        primary: ['Lats'],                     secondary: ['Biceps', 'Core'],                     difficulty: 'intermediate' },
      { name: 'Single Arm Pulldown',       primary: ['Lats'],                     secondary: ['Biceps', 'Core'],                     difficulty: 'intermediate' },
      { name: 'Straight Arm Pulldown',     primary: ['Lats'],                     secondary: ['Triceps', 'Core'],                    difficulty: 'intermediate' },
      { name: 'Seated Cable Row',          primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps', 'Rear Delts'],               difficulty: 'beginner' },
      { name: 'Wide Grip Cable Row',       primary: ['Rhomboids', 'Traps'],       secondary: ['Rear Delts', 'Biceps'],               difficulty: 'beginner' },
      { name: 'Single Arm Cable Row',      primary: ['Lats'],                     secondary: ['Rhomboids', 'Biceps', 'Core'],        difficulty: 'beginner' },
      { name: 'High Cable Row',            primary: ['Rear Delts', 'Rhomboids'],  secondary: ['Biceps', 'Traps'],                    difficulty: 'beginner' },
      { name: 'Cable Bent-Over Row',       primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps'],                             difficulty: 'beginner' },
      { name: 'Cable Shrug',               primary: ['Traps'],                    secondary: ['Rhomboids'],                          difficulty: 'beginner' },
      { name: 'Cable Reverse Fly',         primary: ['Rear Delts'],               secondary: ['Rhomboids', 'Mid Traps'],             difficulty: 'beginner' },
      { name: 'Cable Y Raise',             primary: ['Lower Traps', 'Rear Delts'],secondary: ['Rhomboids'],                          difficulty: 'beginner' },
      { name: 'Face Pull',                 primary: ['Rear Delts'],               secondary: ['Rhomboids', 'Rotator Cuff'],          difficulty: 'beginner' },
      // Chest / Push
      { name: 'Cable Fly (High to Low)',   primary: ['Lower Chest'],              secondary: ['Front Delts'],                        difficulty: 'beginner' },
      { name: 'Cable Fly (Low to High)',   primary: ['Upper Chest'],              secondary: ['Front Delts'],                        difficulty: 'beginner' },
      { name: 'Cable Fly (Mid)',           primary: ['Inner Chest'],              secondary: ['Front Delts'],                        difficulty: 'beginner' },
      { name: 'Single Arm Cable Press',    primary: ['Chest'],                    secondary: ['Triceps', 'Core'],                    difficulty: 'intermediate' },
      { name: 'Cable Around the World',    primary: ['Chest'],                    secondary: ['Front Delts', 'Shoulders'],           difficulty: 'intermediate' },
      // Shoulders
      { name: 'Cable Lateral Raise',       primary: ['Side Delts'],               secondary: ['Traps'],                              difficulty: 'beginner' },
      { name: 'Cable Front Raise',         primary: ['Front Delts'],              secondary: ['Side Delts'],                         difficulty: 'beginner' },
      { name: 'Cable Upright Row',         primary: ['Side Delts', 'Traps'],      secondary: ['Biceps'],                             difficulty: 'beginner' },
      { name: 'Cable Bent-Over Lateral',   primary: ['Rear Delts'],               secondary: ['Rhomboids'],                          difficulty: 'beginner' },
      { name: 'Cable Diagonal Raise',      primary: ['Front Delts', 'Side Delts'],secondary: ['Core'],                               difficulty: 'beginner' },
      { name: 'Cable External Rotation',   primary: ['Rotator Cuff'],             secondary: ['Rear Delts'],                         difficulty: 'beginner' },
      { name: 'Cable Internal Rotation',   primary: ['Rotator Cuff'],             secondary: [],                                     difficulty: 'beginner' },
      { name: 'Cable Overhead Press',      primary: ['Side Delts'],               secondary: ['Triceps', 'Core'],                    difficulty: 'intermediate' },
      // Triceps
      { name: 'Tricep Pushdown (Bar)',     primary: ['Triceps'],                  secondary: [],                                     difficulty: 'beginner' },
      { name: 'Tricep Pushdown (Rope)',    primary: ['Triceps'],                  secondary: [],                                     difficulty: 'beginner' },
      { name: 'Overhead Tricep Ext (cable)',primary: ['Triceps'],                 secondary: [],                                     difficulty: 'beginner' },
      { name: 'Single Arm Tricep Ext',     primary: ['Triceps'],                  secondary: [],                                     difficulty: 'beginner' },
      { name: 'Cable Skull Crusher',       primary: ['Triceps'],                  secondary: [],                                     difficulty: 'intermediate' },
      { name: 'Reverse Grip Pushdown',     primary: ['Triceps', 'Brachialis'],    secondary: [],                                     difficulty: 'beginner' },
      // Biceps
      { name: 'Cable Curl',                primary: ['Biceps'],                   secondary: ['Forearms'],                           difficulty: 'beginner' },
      { name: 'Cable Hammer Curl',         primary: ['Brachialis'],               secondary: ['Biceps', 'Forearms'],                 difficulty: 'beginner' },
      { name: 'Cable Reverse Curl',        primary: ['Brachialis', 'Forearms'],   secondary: ['Biceps'],                             difficulty: 'beginner' },
      { name: 'Cable Drag Curl',           primary: ['Biceps'],                   secondary: ['Brachialis'],                         difficulty: 'intermediate' },
      { name: 'Cable Spider Curl',         primary: ['Biceps'],                   secondary: [],                                     difficulty: 'intermediate' },
      { name: 'Cable Preacher Curl',       primary: ['Biceps'],                   secondary: ['Brachialis'],                         difficulty: 'intermediate' },
      { name: 'Cable Incline Curl',        primary: ['Biceps'],                   secondary: ['Brachialis'],                         difficulty: 'intermediate' },
      // Core / Abs
      { name: 'Cable Crunch',              primary: ['Abs'],                      secondary: ['Hip Flexors'],                        difficulty: 'beginner' },
      { name: 'Kneeling Cable Crunch',     primary: ['Abs'],                      secondary: ['Obliques'],                           difficulty: 'beginner' },
      { name: 'Cable Oblique Crunch',      primary: ['Obliques'],                 secondary: ['Abs'],                                difficulty: 'beginner' },
      { name: 'Wood Chop (High to Low)',   primary: ['Obliques'],                 secondary: ['Core', 'Shoulders'],                  difficulty: 'intermediate' },
      { name: 'Reverse Wood Chop',         primary: ['Obliques', 'Core'],         secondary: ['Shoulders'],                          difficulty: 'intermediate' },
      { name: 'Pallof Press',              primary: ['Core'],                     secondary: ['Obliques'],                           difficulty: 'beginner' },
      { name: 'Cable Dead Bug',            primary: ['Abs', 'Core'],              secondary: ['Hip Flexors'],                        difficulty: 'intermediate' },
      // Lower body
      { name: 'Cable Pull-Through',        primary: ['Glutes'],                   secondary: ['Hamstrings', 'Core'],                 difficulty: 'beginner' },
      { name: 'Cable Kickback (Glute)',     primary: ['Glutes'],                   secondary: ['Hamstrings'],                         difficulty: 'beginner' },
      { name: 'Cable Hip Extension',       primary: ['Glutes'],                   secondary: ['Hamstrings'],                         difficulty: 'beginner' },
      { name: 'Cable Hip Abduction',       primary: ['Glutes', 'Abductors'],      secondary: [],                                     difficulty: 'beginner' },
      { name: 'Cable Hip Adduction',       primary: ['Adductors'],                secondary: ['Glutes'],                             difficulty: 'beginner' },
      { name: 'Cable Single Leg Hip Ext',  primary: ['Glutes'],                   secondary: ['Core', 'Hamstrings'],                 difficulty: 'intermediate' },
      { name: 'Cable Romanian Deadlift',   primary: ['Hamstrings'],               secondary: ['Glutes', 'Lower Back'],               difficulty: 'intermediate' },
      { name: 'Cable Good Morning',        primary: ['Hamstrings', 'Erectors'],   secondary: ['Glutes'],                             difficulty: 'intermediate' },
      { name: 'Cable Deadlift',            primary: ['Glutes', 'Hamstrings'],     secondary: ['Lower Back', 'Core'],                 difficulty: 'intermediate' },
      { name: 'Cable Squat',               primary: ['Quads'],                    secondary: ['Glutes', 'Core'],                     difficulty: 'beginner' },
      { name: 'Cable Lunge',               primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings', 'Core'],                 difficulty: 'intermediate' },
      { name: 'Cable Squat to Row',        primary: ['Quads', 'Lats'],            secondary: ['Glutes', 'Biceps'],                   difficulty: 'intermediate' },
      { name: 'Cable Wrist Curl',          primary: ['Forearms'],                 secondary: [],                                     difficulty: 'beginner' },
      { name: 'Cable Wrist Extension',     primary: ['Forearms'],                 secondary: [],                                     difficulty: 'beginner' },
    ],
  },

  // ─── MACHINES ────────────────────────────────────────────────────────────────
  {
    id: 'smith_machine',
    name: 'Smith Machine',
    icon: 'grid-outline',
    category: 'Machine',
    exercises: [
      // Squats / Lower
      { name: 'Smith Squat',               primary: ['Quads'],                    secondary: ['Glutes', 'Hamstrings'],               difficulty: 'beginner' },
      { name: 'Smith Front Squat',         primary: ['Quads'],                    secondary: ['Core', 'Upper Back'],                 difficulty: 'intermediate' },
      { name: 'Smith Sumo Squat',          primary: ['Glutes', 'Inner Quads'],    secondary: ['Hamstrings', 'Adductors'],            difficulty: 'beginner' },
      { name: 'Smith Hack Squat',          primary: ['Quads'],                    secondary: ['Glutes'],                             difficulty: 'beginner' },
      { name: 'Smith Lunge',               primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings'],                         difficulty: 'beginner' },
      { name: 'Smith Reverse Lunge',       primary: ['Glutes', 'Quads'],          secondary: ['Hamstrings'],                         difficulty: 'beginner' },
      { name: 'Smith Bulgarian Split',     primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings', 'Core'],                 difficulty: 'intermediate' },
      { name: 'Smith Single Leg Squat',    primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings', 'Core'],                 difficulty: 'advanced' },
      { name: 'Smith Step-Up',             primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings'],                         difficulty: 'beginner' },
      // Deadlifts / Hip hinge
      { name: 'Smith Deadlift',            primary: ['Hamstrings', 'Glutes'],     secondary: ['Lower Back', 'Traps'],                difficulty: 'beginner' },
      { name: 'Smith Romanian Deadlift',   primary: ['Hamstrings'],               secondary: ['Glutes', 'Lower Back'],               difficulty: 'beginner' },
      { name: 'Smith Stiff Leg Deadlift',  primary: ['Hamstrings'],               secondary: ['Glutes', 'Lower Back'],               difficulty: 'beginner' },
      { name: 'Smith Good Morning',        primary: ['Hamstrings', 'Erectors'],   secondary: ['Glutes'],                             difficulty: 'intermediate' },
      { name: 'Smith Hip Thrust',          primary: ['Glutes'],                   secondary: ['Hamstrings'],                         difficulty: 'beginner' },
      { name: 'Smith Calf Raise',          primary: ['Calves'],                   secondary: [],                                     difficulty: 'beginner' },
      // Chest / Push
      { name: 'Smith Bench Press',         primary: ['Chest'],                    secondary: ['Triceps', 'Front Delts'],             difficulty: 'beginner' },
      { name: 'Smith Incline Press',       primary: ['Upper Chest'],              secondary: ['Triceps', 'Front Delts'],             difficulty: 'beginner' },
      { name: 'Smith Decline Press',       primary: ['Lower Chest'],              secondary: ['Triceps'],                            difficulty: 'beginner' },
      { name: 'Smith Close Grip Bench',    primary: ['Triceps', 'Chest'],         secondary: ['Front Delts'],                        difficulty: 'intermediate' },
      { name: 'Smith Floor Press',         primary: ['Chest', 'Triceps'],         secondary: ['Front Delts'],                        difficulty: 'intermediate' },
      // Overhead / Shoulders
      { name: 'Smith Overhead Press',      primary: ['Side Delts'],               secondary: ['Triceps'],                            difficulty: 'beginner' },
      { name: 'Smith Behind Neck Press',   primary: ['Rear Delts', 'Side Delts'], secondary: ['Triceps'],                            difficulty: 'advanced' },
      { name: 'Smith Upright Row',         primary: ['Side Delts', 'Traps'],      secondary: ['Biceps'],                             difficulty: 'beginner' },
      // Back / Rows
      { name: 'Smith Bent-Over Row',       primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps'],                             difficulty: 'beginner' },
      { name: 'Smith Yates Row',           primary: ['Lats'],                     secondary: ['Biceps', 'Rhomboids'],                difficulty: 'beginner' },
      { name: 'Smith Inverted Row',        primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps', 'Core'],                     difficulty: 'beginner' },
      { name: 'Smith Behind-Back Shrug',   primary: ['Traps'],                    secondary: ['Rhomboids'],                          difficulty: 'beginner' },
      { name: 'Smith Shrug',               primary: ['Traps'],                    secondary: ['Rhomboids'],                          difficulty: 'beginner' },
      // Arms
      { name: 'Smith Drag Curl',           primary: ['Biceps'],                   secondary: ['Brachialis'],                         difficulty: 'intermediate' },
      { name: 'Smith Curl',                primary: ['Biceps'],                   secondary: ['Forearms'],                           difficulty: 'beginner' },
      { name: 'Smith Skull Crusher',       primary: ['Triceps'],                  secondary: [],                                     difficulty: 'intermediate' },
    ],
  },
  {
    id: 'leg_press',
    name: 'Leg Press Machine',
    icon: 'trending-up-outline',
    category: 'Machine',
    exercises: [
      { name: 'Standard Leg Press',        primary: ['Quads'],                    secondary: ['Glutes', 'Hamstrings'],               difficulty: 'beginner' },
      { name: 'Narrow Stance Press',       primary: ['Outer Quads'],              secondary: ['Glutes'],                             difficulty: 'beginner' },
      { name: 'Wide Stance Press',         primary: ['Glutes', 'Inner Quads'],    secondary: ['Hamstrings', 'Adductors'],            difficulty: 'beginner' },
      { name: 'High Foot Press',           primary: ['Glutes', 'Hamstrings'],     secondary: ['Quads'],                              difficulty: 'beginner' },
      { name: 'Low Foot Press',            primary: ['Quads (VMO)'],              secondary: ['Glutes'],                             difficulty: 'beginner' },
      { name: 'Toes-Out Press',            primary: ['Inner Quads', 'Adductors'], secondary: ['Glutes'],                             difficulty: 'beginner' },
      { name: 'Single Leg Press',          primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings', 'Core'],                 difficulty: 'intermediate' },
      { name: 'Pause Leg Press',           primary: ['Quads'],                    secondary: ['Glutes'],                             difficulty: 'intermediate' },
      { name: 'Tempo Leg Press',           primary: ['Quads'],                    secondary: ['Glutes', 'Hamstrings'],               difficulty: 'intermediate' },
      { name: 'Calf Press',                primary: ['Calves'],                   secondary: [],                                     difficulty: 'beginner' },
    ],
  },
  {
    id: 'hack_squat_machine',
    name: 'Hack Squat Machine',
    icon: 'chevron-down-outline',
    category: 'Machine',
    exercises: [
      { name: 'Hack Squat',                primary: ['Quads'],                    secondary: ['Glutes', 'Hamstrings'],               difficulty: 'beginner' },
      { name: 'Narrow Stance Hack Squat',  primary: ['Outer Quads'],              secondary: ['Glutes'],                             difficulty: 'beginner' },
      { name: 'Wide Stance Hack Squat',    primary: ['Glutes', 'Inner Quads'],    secondary: ['Hamstrings', 'Adductors'],            difficulty: 'beginner' },
      { name: 'High Foot Hack Squat',      primary: ['Glutes', 'Hamstrings'],     secondary: ['Quads'],                              difficulty: 'beginner' },
      { name: 'Low Foot Hack Squat',       primary: ['Quads (VMO)'],              secondary: ['Glutes'],                             difficulty: 'beginner' },
      { name: 'Single Leg Hack Squat',     primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings', 'Core'],                 difficulty: 'intermediate' },
      { name: 'Sumo Hack Squat',           primary: ['Glutes', 'Adductors'],      secondary: ['Inner Quads'],                        difficulty: 'beginner' },
      { name: 'Pause Hack Squat',          primary: ['Quads'],                    secondary: ['Glutes'],                             difficulty: 'intermediate' },
      { name: 'Reverse Hack Squat',        primary: ['Glutes', 'Hamstrings'],     secondary: ['Quads'],                              difficulty: 'intermediate' },
      { name: 'Hack Squat Calf Raise',     primary: ['Calves'],                   secondary: [],                                     difficulty: 'beginner' },
    ],
  },
  {
    id: 'pec_deck',
    name: 'Pec Deck / Fly Machine',
    icon: 'body-outline',
    category: 'Machine',
    exercises: [
      { name: 'Machine Chest Fly',         primary: ['Chest'],                    secondary: ['Front Delts'],                        difficulty: 'beginner' },
      { name: 'Wide Range Chest Fly',      primary: ['Chest'],                    secondary: ['Front Delts'],                        difficulty: 'beginner' },
      { name: 'Single Arm Chest Fly',      primary: ['Chest'],                    secondary: ['Core'],                               difficulty: 'intermediate' },
      { name: 'Reverse Pec Deck',          primary: ['Rear Delts'],               secondary: ['Rhomboids', 'Mid Traps'],             difficulty: 'beginner' },
      { name: 'Incline Reverse Pec Deck',  primary: ['Rear Delts', 'Lower Traps'],secondary: ['Rhomboids'],                          difficulty: 'beginner' },
    ],
  },
  {
    id: 'chest_press_machine',
    name: 'Chest Press Machine',
    icon: 'arrow-forward-outline',
    category: 'Machine',
    exercises: [
      { name: 'Machine Chest Press',       primary: ['Chest'],                    secondary: ['Triceps', 'Front Delts'],             difficulty: 'beginner' },
      { name: 'Wide Grip Chest Press',     primary: ['Chest'],                    secondary: ['Front Delts'],                        difficulty: 'beginner' },
      { name: 'Close Grip Chest Press',    primary: ['Triceps', 'Chest'],         secondary: ['Front Delts'],                        difficulty: 'beginner' },
      { name: 'Incline Machine Press',     primary: ['Upper Chest'],              secondary: ['Triceps', 'Front Delts'],             difficulty: 'beginner' },
      { name: 'Decline Machine Press',     primary: ['Lower Chest'],              secondary: ['Triceps'],                            difficulty: 'beginner' },
      { name: 'Single Arm Press',          primary: ['Chest'],                    secondary: ['Triceps', 'Core'],                    difficulty: 'intermediate' },
      { name: 'Pause Machine Press',       primary: ['Chest'],                    secondary: ['Triceps'],                            difficulty: 'intermediate' },
      { name: '21s Machine Press',         primary: ['Chest'],                    secondary: ['Triceps', 'Front Delts'],             difficulty: 'intermediate' },
    ],
  },
  {
    id: 'shoulder_press_machine',
    name: 'Shoulder Press Machine',
    icon: 'arrow-up-outline',
    category: 'Machine',
    exercises: [
      { name: 'Machine Shoulder Press',    primary: ['Side Delts'],               secondary: ['Triceps', 'Front Delts'],             difficulty: 'beginner' },
      { name: 'Neutral Grip Press',        primary: ['Side Delts'],               secondary: ['Triceps'],                            difficulty: 'beginner' },
      { name: 'Single Arm Machine OHP',    primary: ['Side Delts'],               secondary: ['Triceps', 'Core'],                    difficulty: 'intermediate' },
      { name: 'Alternating Machine Press', primary: ['Side Delts'],               secondary: ['Triceps', 'Core'],                    difficulty: 'intermediate' },
      { name: 'Pause Machine OHP',         primary: ['Side Delts'],               secondary: ['Triceps'],                            difficulty: 'intermediate' },
      { name: 'Machine Arnold Press',      primary: ['Side Delts', 'Front Delts'],secondary: ['Triceps'],                            difficulty: 'intermediate' },
      { name: 'Partial Rep OHP',           primary: ['Side Delts'],               secondary: ['Triceps'],                            difficulty: 'beginner' },
    ],
  },
  {
    id: 'lat_pulldown_machine',
    name: 'Lat Pulldown Machine',
    icon: 'arrow-down-outline',
    category: 'Machine',
    exercises: [
      { name: 'Wide Grip Pulldown',        primary: ['Lats'],                     secondary: ['Biceps', 'Rear Delts'],               difficulty: 'beginner' },
      { name: 'Close Grip Pulldown',       primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps'],                             difficulty: 'beginner' },
      { name: 'Neutral Grip Pulldown',     primary: ['Lats'],                     secondary: ['Biceps'],                             difficulty: 'beginner' },
      { name: 'Underhand Pulldown',        primary: ['Lats', 'Biceps'],           secondary: ['Rhomboids'],                          difficulty: 'beginner' },
      { name: 'V-Bar Pulldown',            primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps'],                             difficulty: 'beginner' },
      { name: 'Rope Pulldown',             primary: ['Lats'],                     secondary: ['Biceps', 'Rear Delts'],               difficulty: 'intermediate' },
      { name: 'Single Arm Pulldown',       primary: ['Lats'],                     secondary: ['Biceps', 'Core'],                     difficulty: 'intermediate' },
      { name: 'Straight Arm Pulldown',     primary: ['Lats'],                     secondary: ['Core', 'Triceps'],                    difficulty: 'intermediate' },
      { name: 'Kneeling Pulldown',         primary: ['Lats'],                     secondary: ['Core', 'Biceps'],                     difficulty: 'intermediate' },
      { name: 'Lean-Back Pulldown',        primary: ['Lats'],                     secondary: ['Biceps', 'Rear Delts'],               difficulty: 'intermediate' },
      { name: 'Behind-Neck Pulldown',      primary: ['Lats', 'Rear Delts'],       secondary: ['Biceps', 'Rhomboids'],                difficulty: 'advanced' },
      { name: 'Supinated Pulldown',        primary: ['Lats', 'Biceps'],           secondary: ['Rhomboids'],                          difficulty: 'beginner' },
      { name: 'Pause Pulldown',            primary: ['Lats'],                     secondary: ['Biceps', 'Rhomboids'],                difficulty: 'intermediate' },
      { name: 'Wide Overhand Pulldown',    primary: ['Lats'],                     secondary: ['Rear Delts', 'Rhomboids'],            difficulty: 'beginner' },
    ],
  },
  {
    id: 'seated_row_machine',
    name: 'Seated Row Machine',
    icon: 'push-outline',
    category: 'Machine',
    exercises: [
      { name: 'Wide Grip Row',             primary: ['Rhomboids', 'Traps'],       secondary: ['Rear Delts', 'Biceps'],               difficulty: 'beginner' },
      { name: 'Narrow Grip Row',           primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps'],                             difficulty: 'beginner' },
      { name: 'Underhand Row',             primary: ['Lats', 'Biceps'],           secondary: ['Rhomboids'],                          difficulty: 'beginner' },
      { name: 'V-Bar Row',                 primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps'],                             difficulty: 'beginner' },
      { name: 'Rope Row',                  primary: ['Rear Delts', 'Rhomboids'],  secondary: ['Biceps', 'Traps'],                    difficulty: 'beginner' },
      { name: 'Single Arm Row',            primary: ['Lats'],                     secondary: ['Rhomboids', 'Biceps', 'Core'],        difficulty: 'intermediate' },
      { name: 'High Row',                  primary: ['Rear Delts', 'Rhomboids'],  secondary: ['Biceps', 'Traps'],                    difficulty: 'beginner' },
      { name: 'Neutral Grip Row',          primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps'],                             difficulty: 'beginner' },
      { name: 'Pause Row',                 primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps'],                             difficulty: 'intermediate' },
      { name: 'Low Row (arms straight)',   primary: ['Lats'],                     secondary: ['Core'],                               difficulty: 'intermediate' },
    ],
  },
  {
    id: 'leg_curl_machine',
    name: 'Leg Curl Machine',
    icon: 'sync-outline',
    category: 'Machine',
    exercises: [
      { name: 'Lying Leg Curl',            primary: ['Hamstrings'],               secondary: ['Glutes', 'Calves'],                   difficulty: 'beginner' },
      { name: 'Seated Leg Curl',           primary: ['Hamstrings'],               secondary: ['Calves'],                             difficulty: 'beginner' },
      { name: 'Single Leg Curl',           primary: ['Hamstrings'],               secondary: ['Glutes'],                             difficulty: 'intermediate' },
      { name: 'Pause Leg Curl',            primary: ['Hamstrings'],               secondary: ['Calves'],                             difficulty: 'intermediate' },
      { name: 'Tempo Leg Curl',            primary: ['Hamstrings'],               secondary: ['Calves', 'Glutes'],                   difficulty: 'intermediate' },
      { name: 'Standing Leg Curl',         primary: ['Hamstrings'],               secondary: ['Glutes'],                             difficulty: 'intermediate' },
      { name: 'Explosive Leg Curl',        primary: ['Hamstrings'],               secondary: ['Glutes', 'Calves'],                   difficulty: 'intermediate' },
      { name: 'Nordic-Style Curl',         primary: ['Hamstrings'],               secondary: ['Glutes', 'Calves'],                   difficulty: 'advanced' },
    ],
  },
  {
    id: 'leg_extension_machine',
    name: 'Leg Extension Machine',
    icon: 'resize-outline',
    category: 'Machine',
    exercises: [
      { name: 'Leg Extension',             primary: ['Quads'],                    secondary: [],                                     difficulty: 'beginner' },
      { name: 'Single Leg Extension',      primary: ['Quads'],                    secondary: [],                                     difficulty: 'beginner' },
      { name: 'Pause Extension',           primary: ['Quads (VMO)'],              secondary: [],                                     difficulty: 'intermediate' },
      { name: 'Toes-Out Extension',        primary: ['Inner Quads'],              secondary: [],                                     difficulty: 'beginner' },
      { name: 'Toes-In Extension',         primary: ['Outer Quads'],              secondary: [],                                     difficulty: 'beginner' },
      { name: 'Tempo Extension',           primary: ['Quads'],                    secondary: [],                                     difficulty: 'intermediate' },
    ],
  },
  {
    id: 'hip_machine',
    name: 'Hip Abductor / Adductor',
    icon: 'git-compare-outline',
    category: 'Machine',
    exercises: [
      { name: 'Hip Abduction (seated)',    primary: ['Glutes', 'Abductors'],      secondary: ['TFL'],                                difficulty: 'beginner' },
      { name: 'Hip Adduction (seated)',    primary: ['Adductors'],                secondary: ['Glutes'],                             difficulty: 'beginner' },
      { name: 'Standing Hip Abduction',    primary: ['Glutes'],                   secondary: ['Abductors', 'Core'],                  difficulty: 'beginner' },
      { name: 'Standing Hip Adduction',    primary: ['Adductors'],                secondary: ['Glutes'],                             difficulty: 'beginner' },
      { name: 'Single Leg Abduction',      primary: ['Glutes', 'Abductors'],      secondary: ['Core'],                               difficulty: 'intermediate' },
    ],
  },
  {
    id: 't_bar_row',
    name: 'T-Bar Row',
    icon: 'swap-vertical-outline',
    category: 'Machine',
    exercises: [
      { name: 'T-Bar Row (wide grip)',     primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps', 'Rear Delts'],               difficulty: 'intermediate' },
      { name: 'T-Bar Row (neutral grip)',  primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps'],                             difficulty: 'intermediate' },
      { name: 'T-Bar Row (close grip)',    primary: ['Lats'],                     secondary: ['Biceps', 'Rhomboids'],                difficulty: 'intermediate' },
      { name: 'T-Bar Row (supinated)',     primary: ['Lats', 'Biceps'],           secondary: ['Rhomboids'],                          difficulty: 'intermediate' },
      { name: 'Chest Supported T-Bar Row',primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps', 'Rear Delts'],               difficulty: 'beginner' },
      { name: 'Single Arm T-Bar Row',      primary: ['Lats'],                     secondary: ['Rhomboids', 'Biceps', 'Core'],        difficulty: 'intermediate' },
      { name: 'T-Bar Shrug',               primary: ['Traps'],                    secondary: ['Rhomboids'],                          difficulty: 'beginner' },
      { name: 'T-Bar Upright Row',         primary: ['Side Delts', 'Traps'],      secondary: ['Biceps'],                             difficulty: 'beginner' },
    ],
  },
  {
    id: 'preacher_curl',
    name: 'Preacher Curl Bench',
    icon: 'hand-left-outline',
    category: 'Machine',
    exercises: [
      { name: 'EZ Bar Preacher Curl',      primary: ['Biceps'],                   secondary: ['Brachialis'],                         difficulty: 'beginner' },
      { name: 'DB Preacher Curl',          primary: ['Biceps'],                   secondary: ['Brachialis'],                         difficulty: 'beginner' },
      { name: 'Barbell Preacher Curl',     primary: ['Biceps'],                   secondary: ['Brachialis'],                         difficulty: 'beginner' },
      { name: 'Reverse Preacher Curl',     primary: ['Brachialis', 'Forearms'],   secondary: ['Biceps'],                             difficulty: 'beginner' },
      { name: 'Hammer Preacher Curl',      primary: ['Brachialis'],               secondary: ['Biceps', 'Forearms'],                 difficulty: 'beginner' },
      { name: 'Cable Preacher Curl',       primary: ['Biceps'],                   secondary: ['Brachialis'],                         difficulty: 'beginner' },
    ],
  },
  {
    id: 'back_extension',
    name: 'Back Extension / GHD',
    icon: 'accessibility-outline',
    category: 'Machine',
    exercises: [
      { name: 'Back Extension',            primary: ['Erectors'],                 secondary: ['Glutes', 'Hamstrings'],               difficulty: 'beginner' },
      { name: '45° Hyperextension',        primary: ['Erectors'],                 secondary: ['Glutes', 'Hamstrings'],               difficulty: 'beginner' },
      { name: 'Weighted Back Extension',   primary: ['Erectors'],                 secondary: ['Glutes', 'Hamstrings'],               difficulty: 'intermediate' },
      { name: 'Back Ext with Rotation',    primary: ['Erectors', 'Obliques'],     secondary: ['Glutes'],                             difficulty: 'intermediate' },
      { name: 'Reverse Hyperextension',    primary: ['Glutes', 'Hamstrings'],     secondary: ['Lower Back'],                         difficulty: 'intermediate' },
      { name: 'GHD Sit-Up',                primary: ['Abs', 'Hip Flexors'],       secondary: ['Core'],                               difficulty: 'advanced' },
      { name: 'Hip Extension Hold',        primary: ['Glutes'],                   secondary: ['Hamstrings', 'Erectors'],             difficulty: 'beginner' },
      { name: 'Back Ext + Shrug',          primary: ['Erectors', 'Traps'],        secondary: ['Glutes', 'Rhomboids'],                difficulty: 'intermediate' },
    ],
  },
  {
    id: 'ab_machine',
    name: 'Ab / Crunch Machine',
    icon: 'albums-outline',
    category: 'Machine',
    exercises: [
      { name: 'Machine Crunch',            primary: ['Abs'],                      secondary: [],                                     difficulty: 'beginner' },
      { name: 'Oblique Machine Crunch',    primary: ['Obliques'],                 secondary: ['Abs'],                                difficulty: 'beginner' },
      { name: 'Decline Machine Crunch',    primary: ['Abs'],                      secondary: [],                                     difficulty: 'beginner' },
      { name: 'Machine Reverse Crunch',    primary: ['Lower Abs'],                secondary: ['Hip Flexors'],                        difficulty: 'beginner' },
      { name: 'Weighted Machine Crunch',   primary: ['Abs'],                      secondary: [],                                     difficulty: 'intermediate' },
      { name: 'Machine Crunch with Twist', primary: ['Obliques'],                 secondary: ['Abs'],                                difficulty: 'intermediate' },
    ],
  },

  // ─── BODYWEIGHT ───────────────────────────────────────────────────────────────
  {
    id: 'pullup_bar',
    name: 'Pull-Up Bar',
    icon: 'fitness-outline',
    category: 'Bodyweight',
    exercises: [
      { name: 'Pull-Up',                   primary: ['Lats'],                     secondary: ['Biceps', 'Rhomboids', 'Core'],        difficulty: 'intermediate' },
      { name: 'Chin-Up',                   primary: ['Lats', 'Biceps'],           secondary: ['Rhomboids'],                          difficulty: 'intermediate' },
      { name: 'Neutral Grip Pull-Up',      primary: ['Lats'],                     secondary: ['Biceps', 'Brachialis'],               difficulty: 'intermediate' },
      { name: 'Wide Grip Pull-Up',         primary: ['Lats'],                     secondary: ['Rear Delts', 'Rhomboids'],            difficulty: 'advanced' },
      { name: 'Close Grip Pull-Up',        primary: ['Lats', 'Biceps'],           secondary: ['Core'],                               difficulty: 'intermediate' },
      { name: 'Mixed Grip Pull-Up',        primary: ['Lats'],                     secondary: ['Biceps', 'Core'],                     difficulty: 'intermediate' },
      { name: 'Scapular Pull-Up',          primary: ['Serratus', 'Lats'],         secondary: ['Rhomboids'],                          difficulty: 'beginner' },
      { name: 'Negative Pull-Up',          primary: ['Lats'],                     secondary: ['Biceps', 'Core'],                     difficulty: 'beginner' },
      { name: 'Chest-to-Bar Pull-Up',      primary: ['Lats'],                     secondary: ['Biceps', 'Rear Delts'],               difficulty: 'advanced' },
      { name: 'Weighted Pull-Up',          primary: ['Lats'],                     secondary: ['Biceps', 'Rhomboids'],                difficulty: 'advanced' },
      { name: 'Typewriter Pull-Up',        primary: ['Lats'],                     secondary: ['Core', 'Biceps'],                     difficulty: 'advanced' },
      { name: 'Archer Pull-Up',            primary: ['Lats'],                     secondary: ['Core', 'Biceps'],                     difficulty: 'advanced' },
      { name: 'Commando Pull-Up',          primary: ['Lats'],                     secondary: ['Biceps', 'Core'],                     difficulty: 'advanced' },
      { name: 'Muscle-Up',                 primary: ['Lats', 'Chest'],            secondary: ['Triceps', 'Core'],                    difficulty: 'advanced' },
      { name: 'Hanging Leg Raise',         primary: ['Abs', 'Hip Flexors'],       secondary: ['Lats'],                               difficulty: 'intermediate' },
      { name: 'Hanging Knee Raise',        primary: ['Abs'],                      secondary: ['Hip Flexors'],                        difficulty: 'beginner' },
      { name: 'Toes to Bar',               primary: ['Abs', 'Hip Flexors'],       secondary: ['Lats', 'Core'],                       difficulty: 'advanced' },
      { name: 'Windshield Wiper',          primary: ['Obliques'],                 secondary: ['Abs', 'Lats'],                        difficulty: 'advanced' },
      { name: 'Hollow Body Hold',          primary: ['Abs', 'Core'],              secondary: ['Lats'],                               difficulty: 'intermediate' },
      { name: 'L-Sit Hang',                primary: ['Abs', 'Hip Flexors'],       secondary: ['Lats', 'Triceps'],                    difficulty: 'advanced' },
      { name: 'Dead Hang',                 primary: ['Grip', 'Lats'],             secondary: ['Shoulders'],                          difficulty: 'beginner' },
      { name: 'Active Hang',               primary: ['Lats', 'Serratus'],         secondary: ['Shoulders'],                          difficulty: 'beginner' },
      { name: 'Around the World',          primary: ['Lats', 'Core'],             secondary: ['Biceps', 'Shoulders'],                difficulty: 'advanced' },
      { name: 'Behind-Neck Pull-Up',       primary: ['Lats', 'Rear Delts'],       secondary: ['Biceps', 'Rhomboids'],                difficulty: 'advanced' },
    ],
  },
  {
    id: 'dip_bars',
    name: 'Dip Bars',
    icon: 'git-commit-outline',
    category: 'Bodyweight',
    exercises: [
      { name: 'Tricep Dip',                primary: ['Triceps'],                  secondary: ['Chest', 'Front Delts'],               difficulty: 'intermediate' },
      { name: 'Chest Dip',                 primary: ['Lower Chest'],              secondary: ['Triceps', 'Front Delts'],             difficulty: 'intermediate' },
      { name: 'Assisted Dip',              primary: ['Triceps', 'Chest'],         secondary: ['Shoulders'],                          difficulty: 'beginner' },
      { name: 'Negative Dip',              primary: ['Triceps', 'Chest'],         secondary: ['Front Delts'],                        difficulty: 'beginner' },
      { name: 'Weighted Dip',              primary: ['Triceps', 'Chest'],         secondary: ['Front Delts'],                        difficulty: 'advanced' },
      { name: 'Bulgarian Dip',             primary: ['Front Delts', 'Chest'],     secondary: ['Triceps'],                            difficulty: 'advanced' },
      { name: 'Korean Dip',                primary: ['Front Delts'],              secondary: ['Biceps', 'Triceps', 'Core'],          difficulty: 'advanced' },
      { name: 'Russian Dip',               primary: ['Triceps'],                  secondary: ['Chest', 'Core'],                      difficulty: 'advanced' },
      { name: 'L-Sit Hold',                primary: ['Abs', 'Hip Flexors'],       secondary: ['Triceps'],                            difficulty: 'advanced' },
      { name: 'Straight Bar Dip',          primary: ['Chest', 'Triceps'],         secondary: ['Front Delts', 'Core'],                difficulty: 'advanced' },
      { name: 'Parallel Bar Push-Up',      primary: ['Chest'],                    secondary: ['Triceps', 'Front Delts'],             difficulty: 'beginner' },
      { name: 'Pike Press on Bars',        primary: ['Front Delts', 'Triceps'],   secondary: ['Core'],                               difficulty: 'intermediate' },
    ],
  },

  // ─── ACCESSORIES ─────────────────────────────────────────────────────────────
  {
    id: 'resistance_bands',
    name: 'Resistance Bands',
    icon: 'ellipse-outline',
    category: 'Accessories',
    exercises: [
      // Upper
      { name: 'Band Pull-Apart',           primary: ['Rear Delts'],               secondary: ['Rhomboids', 'Mid Traps'],             difficulty: 'beginner' },
      { name: 'Band Face Pull',            primary: ['Rear Delts'],               secondary: ['Rotator Cuff'],                       difficulty: 'beginner' },
      { name: 'Band Overhead Press',       primary: ['Side Delts'],               secondary: ['Triceps', 'Front Delts'],             difficulty: 'beginner' },
      { name: 'Band Lateral Raise',        primary: ['Side Delts'],               secondary: ['Traps'],                              difficulty: 'beginner' },
      { name: 'Band Front Raise',          primary: ['Front Delts'],              secondary: ['Side Delts'],                         difficulty: 'beginner' },
      { name: 'Band Reverse Fly',          primary: ['Rear Delts'],               secondary: ['Rhomboids', 'Mid Traps'],             difficulty: 'beginner' },
      { name: 'Band Diagonal Raise',       primary: ['Front Delts', 'Side Delts'],secondary: ['Core'],                               difficulty: 'beginner' },
      { name: 'Band Shoulder ER',          primary: ['Rotator Cuff'],             secondary: ['Rear Delts'],                         difficulty: 'beginner' },
      { name: 'Band Shoulder IR',          primary: ['Rotator Cuff'],             secondary: [],                                     difficulty: 'beginner' },
      { name: 'Band Curl',                 primary: ['Biceps'],                   secondary: ['Forearms'],                           difficulty: 'beginner' },
      { name: 'Band Hammer Curl',          primary: ['Brachialis'],               secondary: ['Biceps', 'Forearms'],                 difficulty: 'beginner' },
      { name: 'Band Tricep Pushdown',      primary: ['Triceps'],                  secondary: [],                                     difficulty: 'beginner' },
      { name: 'Band Overhead Tricep Ext',  primary: ['Triceps'],                  secondary: [],                                     difficulty: 'beginner' },
      { name: 'Band Row (seated/standing)',primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps'],                             difficulty: 'beginner' },
      { name: 'Band Straight Arm Pulldown',primary: ['Lats'],                     secondary: ['Triceps', 'Core'],                    difficulty: 'beginner' },
      { name: 'Band Chest Press',          primary: ['Chest'],                    secondary: ['Triceps', 'Front Delts'],             difficulty: 'beginner' },
      { name: 'Band Assisted Pull-Up',     primary: ['Lats'],                     secondary: ['Biceps', 'Rhomboids'],                difficulty: 'beginner' },
      { name: 'Band Assisted Dip',         primary: ['Triceps', 'Chest'],         secondary: ['Shoulders'],                          difficulty: 'beginner' },
      // Lower
      { name: 'Banded Squat',              primary: ['Quads'],                    secondary: ['Glutes'],                             difficulty: 'beginner' },
      { name: 'Banded Hip Thrust',         primary: ['Glutes'],                   secondary: ['Hamstrings'],                         difficulty: 'beginner' },
      { name: 'Banded Glute Bridge',       primary: ['Glutes'],                   secondary: ['Core'],                               difficulty: 'beginner' },
      { name: 'Banded Romanian Deadlift',  primary: ['Hamstrings'],               secondary: ['Glutes'],                             difficulty: 'beginner' },
      { name: 'Banded Good Morning',       primary: ['Hamstrings', 'Erectors'],   secondary: ['Glutes'],                             difficulty: 'beginner' },
      { name: 'Band Lateral Walk',         primary: ['Glutes', 'Abductors'],      secondary: [],                                     difficulty: 'beginner' },
      { name: 'Band Monster Walk',         primary: ['Glutes', 'Abductors'],      secondary: ['Quads'],                              difficulty: 'beginner' },
      { name: 'Band Donkey Kick',          primary: ['Glutes'],                   secondary: ['Hamstrings'],                         difficulty: 'beginner' },
      { name: 'Band Fire Hydrant',         primary: ['Glutes', 'Abductors'],      secondary: ['Core'],                               difficulty: 'beginner' },
      { name: 'Band Clamshell',            primary: ['Glutes', 'Abductors'],      secondary: [],                                     difficulty: 'beginner' },
      { name: 'Band Lying Hip Abduction',  primary: ['Glutes', 'Abductors'],      secondary: [],                                     difficulty: 'beginner' },
      { name: 'Banded Lunge',              primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings'],                         difficulty: 'beginner' },
      { name: 'Band Deadlift',             primary: ['Glutes', 'Hamstrings'],     secondary: ['Lower Back', 'Core'],                 difficulty: 'beginner' },
      // Core
      { name: 'Band Pallof Press',         primary: ['Core'],                     secondary: ['Obliques'],                           difficulty: 'beginner' },
      { name: 'Band Superman',             primary: ['Erectors', 'Glutes'],       secondary: ['Hamstrings', 'Rear Delts'],           difficulty: 'beginner' },
      { name: 'Band Woodchop',             primary: ['Obliques', 'Core'],         secondary: ['Shoulders'],                          difficulty: 'beginner' },
    ],
  },
  {
    id: 'landmine',
    name: 'Landmine',
    icon: 'radio-button-on-outline',
    category: 'Accessories',
    exercises: [
      { name: 'Landmine Press (standing)', primary: ['Front Delts', 'Chest'],     secondary: ['Triceps', 'Core'],                    difficulty: 'intermediate' },
      { name: 'Landmine Press (kneeling)', primary: ['Front Delts', 'Chest'],     secondary: ['Triceps', 'Core'],                    difficulty: 'intermediate' },
      { name: 'Landmine Single Arm Press', primary: ['Front Delts'],              secondary: ['Triceps', 'Core'],                    difficulty: 'intermediate' },
      { name: 'Landmine Push Press',       primary: ['Shoulders'],                secondary: ['Quads', 'Triceps', 'Core'],           difficulty: 'intermediate' },
      { name: 'Landmine Shoulder Press',   primary: ['Side Delts'],               secondary: ['Triceps', 'Core'],                    difficulty: 'intermediate' },
      { name: 'Landmine Row',              primary: ['Lats', 'Rhomboids'],        secondary: ['Biceps', 'Core'],                     difficulty: 'intermediate' },
      { name: 'Landmine Single Arm Row',   primary: ['Lats'],                     secondary: ['Rhomboids', 'Biceps', 'Core'],        difficulty: 'intermediate' },
      { name: 'Landmine Squat',            primary: ['Quads', 'Glutes'],          secondary: ['Core'],                               difficulty: 'beginner' },
      { name: 'Landmine Romanian Deadlift',primary: ['Hamstrings'],               secondary: ['Glutes', 'Lower Back'],               difficulty: 'intermediate' },
      { name: 'Landmine Deadlift',         primary: ['Glutes', 'Hamstrings'],     secondary: ['Core', 'Lower Back'],                 difficulty: 'intermediate' },
      { name: 'Landmine Lunge',            primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings', 'Core'],                 difficulty: 'intermediate' },
      { name: 'Landmine Rotation',         primary: ['Obliques'],                 secondary: ['Core', 'Shoulders'],                  difficulty: 'intermediate' },
      { name: 'Landmine Thruster',         primary: ['Quads', 'Shoulders'],       secondary: ['Glutes', 'Triceps', 'Core'],          difficulty: 'advanced' },
      { name: 'Landmine Hip Hinge',        primary: ['Glutes', 'Hamstrings'],     secondary: ['Lower Back'],                         difficulty: 'beginner' },
    ],
  },
  {
    id: 'kettlebell',
    name: 'Kettlebell',
    icon: 'barbell-outline',
    category: 'Accessories',
    exercises: [
      { name: 'KB Swing (Russian)',         primary: ['Glutes', 'Hamstrings'],     secondary: ['Lower Back', 'Core'],                 difficulty: 'beginner' },
      { name: 'KB Swing (American)',        primary: ['Glutes', 'Shoulders'],      secondary: ['Core', 'Hamstrings'],                 difficulty: 'intermediate' },
      { name: 'KB Goblet Squat',           primary: ['Quads', 'Glutes'],          secondary: ['Core'],                               difficulty: 'beginner' },
      { name: 'KB Sumo Deadlift',          primary: ['Glutes', 'Inner Thighs'],   secondary: ['Hamstrings', 'Lower Back'],            difficulty: 'beginner' },
      { name: 'KB Romanian Deadlift',      primary: ['Hamstrings'],               secondary: ['Glutes', 'Lower Back'],               difficulty: 'beginner' },
      { name: 'KB Single Leg Deadlift',    primary: ['Hamstrings', 'Glutes'],     secondary: ['Core'],                               difficulty: 'intermediate' },
      { name: 'KB Clean',                  primary: ['Full Body', 'Glutes'],      secondary: ['Shoulders', 'Core'],                  difficulty: 'intermediate' },
      { name: 'KB Snatch',                 primary: ['Full Body', 'Shoulders'],   secondary: ['Glutes', 'Core'],                     difficulty: 'advanced' },
      { name: 'KB Press (single arm)',     primary: ['Side Delts'],               secondary: ['Triceps', 'Core'],                    difficulty: 'beginner' },
      { name: 'KB Bottoms-Up Press',       primary: ['Side Delts', 'Core'],       secondary: ['Rotator Cuff', 'Triceps'],            difficulty: 'intermediate' },
      { name: 'KB Row (single arm)',        primary: ['Lats'],                     secondary: ['Rhomboids', 'Biceps'],                difficulty: 'beginner' },
      { name: 'KB Turkish Get-Up',         primary: ['Full Body', 'Core'],        secondary: ['Shoulders', 'Glutes'],                difficulty: 'advanced' },
      { name: 'KB Windmill',               primary: ['Obliques', 'Core'],         secondary: ['Shoulders', 'Hamstrings'],            difficulty: 'advanced' },
      { name: 'KB Halo',                   primary: ['Shoulders', 'Core'],        secondary: ['Triceps'],                            difficulty: 'beginner' },
      { name: 'KB Front Squat',            primary: ['Quads', 'Glutes'],          secondary: ['Core', 'Shoulders'],                  difficulty: 'intermediate' },
      { name: 'KB Figure 8',               primary: ['Core', 'Glutes'],           secondary: ['Shoulders', 'Adductors'],             difficulty: 'intermediate' },
      { name: 'KB Farmer\'s Carry',        primary: ['Grip', 'Traps'],            secondary: ['Core', 'Calves'],                     difficulty: 'beginner' },
      { name: 'KB Lunge',                  primary: ['Quads', 'Glutes'],          secondary: ['Hamstrings'],                         difficulty: 'beginner' },
      { name: 'KB Thruster',               primary: ['Quads', 'Shoulders'],       secondary: ['Glutes', 'Triceps', 'Core'],          difficulty: 'intermediate' },
      { name: 'KB Lateral Lunge',          primary: ['Adductors', 'Glutes'],      secondary: ['Quads'],                              difficulty: 'beginner' },
    ],
  },
  {
    id: 'battle_ropes',
    name: 'Battle Ropes',
    icon: 'pulse-outline',
    category: 'Accessories',
    exercises: [
      { name: 'Alternating Waves',         primary: ['Shoulders', 'Arms'],        secondary: ['Core'],                               difficulty: 'beginner' },
      { name: 'Double Arm Waves',          primary: ['Shoulders', 'Core'],        secondary: ['Arms'],                               difficulty: 'beginner' },
      { name: 'Rope Slams',                primary: ['Shoulders', 'Lats'],        secondary: ['Core', 'Arms'],                       difficulty: 'beginner' },
      { name: 'Side-to-Side Waves',        primary: ['Obliques', 'Core'],         secondary: ['Shoulders'],                          difficulty: 'beginner' },
      { name: 'Clockwise Circles',         primary: ['Shoulders'],                secondary: ['Core', 'Arms'],                       difficulty: 'beginner' },
      { name: 'Counter-Clockwise Circles', primary: ['Shoulders'],                secondary: ['Core', 'Arms'],                       difficulty: 'beginner' },
      { name: 'In-Out Waves',              primary: ['Chest', 'Shoulders'],       secondary: ['Core'],                               difficulty: 'beginner' },
      { name: 'Squat + Waves',             primary: ['Quads', 'Shoulders'],       secondary: ['Glutes', 'Core'],                     difficulty: 'intermediate' },
      { name: 'Lunge + Waves',             primary: ['Quads', 'Shoulders'],       secondary: ['Glutes'],                             difficulty: 'intermediate' },
      { name: 'Plank + Alternating Waves', primary: ['Core', 'Shoulders'],        secondary: ['Arms'],                               difficulty: 'intermediate' },
    ],
  },
];

export const MACHINE_DIFF_COLORS = {
  beginner:     '#4CAF50',
  intermediate: '#FF9800',
  advanced:     '#F44336',
} as const;

export const MACHINE_CATEGORY_ORDER = [
  'Free Weights', 'Cable', 'Machine', 'Bodyweight', 'Accessories',
] as const;
